interface DebateRecapProps {
  recapText: string;
  generatedAt: string;
  forVotes: number;
  againstVotes: number;
}

export default function DebateRecap({
  recapText,
  generatedAt,
  forVotes,
  againstVotes,
}: DebateRecapProps) {
  const total = forVotes + againstVotes;
  const forPct = total > 0 ? Math.round((forVotes / total) * 100) : 50;
  const againstPct = 100 - forPct;

  return (
    <div className="mt-10 rounded-2xl border border-gray-200 bg-white p-6">
      <div className="mb-4 flex items-center justify-between">
        <h2 className="font-display text-lg font-bold text-gray-900">
          Debate Recap
        </h2>
        <span className="rounded-full bg-gray-100 px-2.5 py-1 text-xs text-gray-400">
          Generated by Claude
        </span>
      </div>
      <div className="mt-4 mb-6">
        <div className="mb-1 flex justify-between text-xs">
          <span className="font-medium text-emerald-700">FOR · {forPct}%</span>
          <span className="font-medium text-amber-700">
            {againstPct}% · AGAINST
          </span>
        </div>
        <div className="flex h-2 overflow-hidden rounded-full">
          <div
            className="bg-emerald-500 transition-all duration-700"
            style={{ width: `${forPct}%` }}
          />
          <div
            className="bg-amber-400 transition-all duration-700"
            style={{ width: `${againstPct}%` }}
          />
        </div>
        <p className="mt-1 text-xs text-gray-400">{total} votes cast</p>
      </div>
      <div className="prose prose-sm max-w-none leading-relaxed text-gray-700">
        {recapText.split("\n\n").map((paragraph, index) => (
          <p key={index} className="mb-4 last:mb-0">
            {paragraph}
          </p>
        ))}
      </div>
      <p className="mt-4 text-xs text-gray-400">
        Recap generated{" "}
        {new Date(generatedAt).toLocaleDateString("en-GB", {
          day: "numeric",
          month: "long",
          year: "numeric",
        })}
      </p>
    </div>
  );
}
