interface DebateRecapProps {
  recapText: string;
  generatedAt: string;
}

export default function DebateRecap({
  recapText,
  generatedAt,
}: DebateRecapProps) {
  return (
    <div className="mt-10 rounded-2xl border border-gray-200 bg-white p-6">
      <div className="mb-4 flex items-center justify-between">
        <h2 className="font-display text-lg font-bold text-gray-900">
          Debate Recap
        </h2>
        <span className="rounded-full bg-gray-100 px-2.5 py-1 text-xs text-gray-400">
          Generated by Claude
        </span>
      </div>
      <div className="prose prose-sm max-w-none leading-relaxed text-gray-700">
        {recapText.split("\n\n").map((paragraph, index) => (
          <p key={index} className="mb-4 last:mb-0">
            {paragraph}
          </p>
        ))}
      </div>
      <p className="mt-4 text-xs text-gray-400">
        Recap generated{" "}
        {new Date(generatedAt).toLocaleDateString("en-GB", {
          day: "numeric",
          month: "long",
          year: "numeric",
        })}
      </p>
    </div>
  );
}
