import { StanceMeter, StatTile, getVoteSplit } from "../DebatePrimitives";

interface DebateRecapProps {
  recapText: string;
  generatedAt: string;
  forVotes: number;
  againstVotes: number;
}

export default function DebateRecap({
  recapText,
  generatedAt,
  forVotes,
  againstVotes,
}: DebateRecapProps) {
  const split = getVoteSplit(forVotes, againstVotes);
  const generatedDate = new Date(generatedAt).toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
  const verdict =
    forVotes > againstVotes
      ? "Community voted for the motion"
      : againstVotes > forVotes
        ? "Community voted against the motion"
        : "Community verdict split";

  return (
    <section className="mt-10 rounded-xl border border-gray-200 bg-white p-6">
      <div className="mb-6 flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
        <div>
          <p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-brand">
            Archived recap
          </p>
          <h2 className="font-display mt-1 text-2xl font-bold text-gray-900">
            Debate Recap
          </h2>
          <p className="mt-1 text-sm leading-6 text-gray-500">
            {verdict}. Recap generated {generatedDate}.
          </p>
        </div>
        <span className="w-fit rounded-full bg-gray-100 px-2.5 py-1 text-xs font-medium text-gray-500">
          Generated by Claude
        </span>
      </div>

      <div className="mb-6 grid gap-3 md:grid-cols-[minmax(0,1fr)_220px] md:items-stretch">
        <div className="rounded-xl border border-gray-100 bg-canvas p-4">
          <StanceMeter
            forCount={forVotes}
            againstCount={againstVotes}
            label="Final verdict"
          />
        </div>
        <div className="grid grid-cols-2 gap-2 md:grid-cols-1">
          <StatTile label="votes cast" value={split.total} />
          <StatTile
            label="winning side"
            value={
              forVotes === againstVotes
                ? "Split"
                : forVotes > againstVotes
                  ? "For"
                  : "Against"
            }
            tone={forVotes >= againstVotes ? "emerald" : "amber"}
          />
        </div>
      </div>

      <div className="prose prose-sm max-w-none rounded-xl border border-gray-100 bg-white leading-7 text-gray-700">
        {recapText.split("\n\n").map((paragraph, index) => (
          <p key={index} className="mb-4 px-5 first:pt-5 last:mb-0 last:pb-5">
            {paragraph}
          </p>
        ))}
      </div>
    </section>
  );
}
