-- RELEASE-GATED ADDITIVE MIGRATION CANDIDATE — DO NOT APPLY DIRECTLY.
--
-- Promote only after the deployed Author/Topic migration versions have been
-- reconciled with the local migration ledger. Assign a later timestamp at
-- promotion time. This file deliberately performs no historical event backfill.

create table if not exists public.author_subscription_events (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null check (event_type in ('subscribed', 'unsubscribed')),
  reason text not null check (
    reason in ('subscribe', 'unsubscribe', 'unfollow', 'blocked', 'other')
  ),
  source text not null default 'unknown' check (
    source in (
      'unknown',
      'profile',
      'post_header',
      'author_card',
      'research_sidebar',
      'explore',
      'home_suggestion',
      'onboarding',
      'subscriptions_manager',
      'subscriptions_manager_undo',
      'follow_nudge',
      'qualified_read_nudge'
    )
  ),
  source_post_id uuid references public.posts(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists author_subscription_events_author_created_idx
  on public.author_subscription_events(author_id, created_at desc);
create index if not exists author_subscription_events_source_post_idx
  on public.author_subscription_events(source_post_id, created_at desc)
  where source_post_id is not null;

alter table public.author_subscription_events enable row level security;
revoke all on public.author_subscription_events from public, anon, authenticated;
grant select, insert, update, delete on public.author_subscription_events
  to service_role;
grant usage, select on sequence public.author_subscription_events_id_seq
  to service_role;

create or replace function public.capture_author_subscription_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_source text := coalesce(
    nullif(current_setting('app.author_subscription_source', true), ''),
    'unknown'
  );
  v_reason text := coalesce(
    nullif(current_setting('app.author_subscription_reason', true), ''),
    case when tg_op = 'INSERT' then 'subscribe' else 'other' end
  );
  v_source_post_id uuid;
begin
  if v_source not in (
    'unknown', 'profile', 'post_header', 'author_card', 'research_sidebar',
    'explore', 'home_suggestion', 'onboarding', 'subscriptions_manager',
    'subscriptions_manager_undo', 'follow_nudge', 'qualified_read_nudge'
  ) then
    v_source := 'unknown';
  end if;
  if v_reason not in ('subscribe', 'unsubscribe', 'unfollow', 'blocked', 'other') then
    v_reason := 'other';
  end if;

  begin
    v_source_post_id := nullif(
      current_setting('app.author_subscription_source_post_id', true),
      ''
    )::uuid;
  exception when invalid_text_representation then
    v_source_post_id := null;
  end;

  insert into public.author_subscription_events (
    author_id,
    event_type,
    reason,
    source,
    source_post_id
  )
  values (
    case when tg_op = 'INSERT' then new.author_id else old.author_id end,
    case when tg_op = 'INSERT' then 'subscribed' else 'unsubscribed' end,
    v_reason,
    v_source,
    v_source_post_id
  );
  if tg_op = 'INSERT' then
    return new;
  end if;
  return old;
end;
$$;

drop trigger if exists author_subscriptions_capture_ux_event
  on public.author_subscriptions;
create trigger author_subscriptions_capture_ux_event
after insert or delete on public.author_subscriptions
for each row execute function public.capture_author_subscription_event();

create or replace function public.set_author_relationship_v2(
  p_author_id uuid,
  p_following boolean default null,
  p_subscribed boolean default null,
  p_source text default 'unknown',
  p_source_post_id uuid default null
)
returns table (
  following boolean,
  subscribed boolean,
  follow_created boolean,
  subscription_created boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_subscriber_id uuid := auth.uid();
  v_follow_created boolean := false;
  v_subscription_created boolean := false;
  v_row_count integer := 0;
begin
  if v_subscriber_id is null then
    raise exception 'Authentication required';
  end if;
  if p_author_id is null or p_author_id = v_subscriber_id then
    raise exception 'You cannot follow or subscribe to yourself';
  end if;
  if p_source not in (
    'unknown', 'profile', 'post_header', 'author_card', 'research_sidebar',
    'explore', 'home_suggestion', 'onboarding', 'subscriptions_manager',
    'subscriptions_manager_undo', 'follow_nudge', 'qualified_read_nudge'
  ) then
    raise exception 'Invalid relationship source';
  end if;
  if not exists (select 1 from public.profiles where id = p_author_id) then
    raise exception 'Author not found';
  end if;
  if exists (
    select 1 from public.user_blocks
    where (blocker_id = v_subscriber_id and blocked_id = p_author_id)
       or (blocker_id = p_author_id and blocked_id = v_subscriber_id)
  ) then
    raise exception 'This relationship is unavailable';
  end if;
  if p_source_post_id is not null and not exists (
    select 1
    from public.posts p
    where p.id = p_source_post_id
      and (
        p.author_id = p_author_id
        or exists (
          select 1
          from public.post_authors pa
          where pa.post_id = p.id
            and pa.user_id = p_author_id
            and pa.accepted_at is not null
        )
      )
  ) then
    raise exception 'The source publication does not credit this author';
  end if;

  perform set_config('app.author_subscription_source', p_source, true);
  perform set_config(
    'app.author_subscription_source_post_id',
    coalesce(p_source_post_id::text, ''),
    true
  );
  perform set_config(
    'app.author_subscription_reason',
    case
      when p_following is false then 'unfollow'
      when p_subscribed is false then 'unsubscribe'
      when p_subscribed is true then 'subscribe'
      else 'other'
    end,
    true
  );

  if p_following is false then
    delete from public.author_subscriptions
    where subscriber_id = v_subscriber_id and author_id = p_author_id;
    delete from public.follows
    where follower_id = v_subscriber_id and following_id = p_author_id;
  else
    if p_following is true or p_subscribed is true then
      insert into public.follows (follower_id, following_id)
      values (v_subscriber_id, p_author_id)
      on conflict (follower_id, following_id) do nothing;
      get diagnostics v_row_count = row_count;
      v_follow_created := v_row_count > 0;
    end if;

    if p_subscribed is true then
      insert into public.author_subscriptions (subscriber_id, author_id)
      values (v_subscriber_id, p_author_id)
      on conflict (subscriber_id, author_id) do nothing;
      get diagnostics v_row_count = row_count;
      v_subscription_created := v_row_count > 0;
    elsif p_subscribed is false then
      delete from public.author_subscriptions
      where subscriber_id = v_subscriber_id and author_id = p_author_id;
    end if;
  end if;

  return query
  select
    exists (
      select 1 from public.follows
      where follower_id = v_subscriber_id and following_id = p_author_id
    ),
    exists (
      select 1 from public.author_subscriptions
      where subscriber_id = v_subscriber_id and author_id = p_author_id
    ),
    v_follow_created,
    v_subscription_created;
end;
$$;

revoke all on function public.set_author_relationship_v2(
  uuid, boolean, boolean, text, uuid
) from public, anon;
grant execute on function public.set_author_relationship_v2(
  uuid, boolean, boolean, text, uuid
) to authenticated;

-- Preserve the deployed V1 three-column result signature for rollback
-- compatibility while routing it through the same invariant and event-reason
-- handling as V2. PostgreSQL cannot change an existing function's OUT
-- parameters with CREATE OR REPLACE, so the fourth V2-only transition field
-- must not be exposed from this legacy signature.
create or replace function public.set_author_relationship(
  p_author_id uuid,
  p_following boolean default null,
  p_subscribed boolean default null
)
returns table (
  following boolean,
  subscribed boolean,
  follow_created boolean
)
language sql
security definer
set search_path = public
as $$
  select result.following, result.subscribed, result.follow_created
  from public.set_author_relationship_v2(
    p_author_id,
    p_following,
    p_subscribed,
    'unknown',
    null
  ) result;
$$;

revoke all on function public.set_author_relationship(uuid, boolean, boolean)
  from public, anon;
grant execute on function public.set_author_relationship(uuid, boolean, boolean)
  to authenticated;

-- Blocking supplies a reason before the existing after-insert block trigger
-- removes subscriptions in both directions.
create or replace function public.remove_author_subscriptions_for_block()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform set_config('app.author_subscription_source', 'unknown', true);
  perform set_config('app.author_subscription_reason', 'blocked', true);
  perform set_config('app.author_subscription_source_post_id', '', true);
  delete from public.author_subscriptions
  where (subscriber_id = new.blocker_id and author_id = new.blocked_id)
     or (subscriber_id = new.blocked_id and author_id = new.blocker_id);
  return new;
end;
$$;

create or replace function public.set_notification_preference(
  p_key text,
  p_enabled boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_preferences jsonb;
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;
  if p_key not in (
    'inapp_likes', 'inapp_follows', 'inapp_debates',
    'inapp_collaboration',
    'email_comments', 'email_follows', 'email_likes', 'email_responses',
    'email_messages', 'email_published', 'email_digest',
    'email_account_security', 'email_profile_reminders',
    'email_review_assigned', 'email_review_started', 'email_review_reminder',
    'email_co_author_invite', 'email_co_author_accepted',
    'email_co_author_declined', 'email_opportunity_inquiry',
    'email_author_publications', 'email_debate_updates', 'push_published',
    'push_messages', 'push_comments', 'push_likes', 'push_follows',
    'push_daily_brief', 'push_author_publications', 'push_debate_updates'
  ) then
    raise exception 'Unsupported notification preference';
  end if;

  update public.profiles
  set notification_prefs = jsonb_set(
    coalesce(notification_prefs, '{}'::jsonb),
    array[p_key],
    to_jsonb(p_enabled),
    true
  )
  where id = v_user_id
  returning notification_prefs into v_preferences;

  return v_preferences;
end;
$$;

revoke all on function public.set_notification_preference(text, boolean)
  from public, anon;
grant execute on function public.set_notification_preference(text, boolean)
  to authenticated;

create or replace function public.list_my_author_subscriptions(
  p_search text default '',
  p_sort text default 'recent',
  p_limit integer default 30,
  p_offset integer default 0
)
returns table (
  author_id uuid,
  username text,
  full_name text,
  avatar_url text,
  subscribed_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select s.author_id, p.username, p.full_name, p.avatar_url, s.created_at
  from public.author_subscriptions s
  join public.profiles p on p.id = s.author_id
  where s.subscriber_id = auth.uid()
    and (
      coalesce(p_search, '') = ''
      or p.username ilike '%' || p_search || '%'
      or coalesce(p.full_name, '') ilike '%' || p_search || '%'
    )
  order by
    case when p_sort = 'az' then lower(coalesce(p.full_name, p.username)) end asc,
    case when p_sort <> 'az' then s.created_at end desc,
    s.author_id
  limit least(greatest(p_limit, 1), 30)
  offset greatest(p_offset, 0);
$$;

create or replace function public.list_my_topic_subscriptions(
  p_search text default '',
  p_sort text default 'recent',
  p_limit integer default 30,
  p_offset integer default 0
)
returns table (
  topic_key text,
  display_label text,
  subscribed_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select s.topic_key, s.display_label, s.created_at
  from public.topic_subscriptions s
  where s.subscriber_id = auth.uid()
    and (
      coalesce(p_search, '') = ''
      or s.display_label ilike '%' || p_search || '%'
    )
  order by
    case when p_sort = 'az' then lower(s.display_label) end asc,
    case when p_sort <> 'az' then s.created_at end desc,
    s.topic_key
  limit least(greatest(p_limit, 1), 30)
  offset greatest(p_offset, 0);
$$;

revoke all on function public.list_my_author_subscriptions(
  text, text, integer, integer
) from public, anon;
revoke all on function public.list_my_topic_subscriptions(
  text, text, integer, integer
) from public, anon;
grant execute on function public.list_my_author_subscriptions(
  text, text, integer, integer
) to authenticated;
grant execute on function public.list_my_topic_subscriptions(
  text, text, integer, integer
) to authenticated;

create or replace function public.get_subscription_feed_candidates(
  p_source text default 'all',
  p_content_kind text default null,
  p_published_before timestamptz default null,
  p_id_before uuid default null,
  p_limit integer default 30
)
returns table (
  post_id uuid,
  matched_author_ids uuid[],
  matched_topic_keys text[],
  published_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  with candidate as (
    select
      p.id as post_id,
      p.published_at,
      array(
        select distinct matched.author_id
        from (
          select s.author_id
          from public.author_subscriptions s
          where s.subscriber_id = auth.uid() and s.author_id = p.author_id
          union
          select s.author_id
          from public.author_subscriptions s
          join public.post_authors pa
            on pa.user_id = s.author_id
           and pa.post_id = p.id
           and pa.accepted_at is not null
          where s.subscriber_id = auth.uid()
        ) matched
      ) as matched_author_ids,
      array(
        select ts.topic_key
        from public.topic_subscriptions ts
        where ts.subscriber_id = auth.uid()
          and ts.topic_key = any(coalesce(p.topic_keys, '{}'::text[]))
      ) as matched_topic_keys
    from public.posts p
    where auth.uid() is not null
      and p.status = 'published'
      and (p_content_kind is null or p.content_kind = p_content_kind)
      and p.author_id <> auth.uid()
      and not exists (
        select 1 from public.post_authors own_credit
        where own_credit.post_id = p.id
          and own_credit.user_id = auth.uid()
          and own_credit.accepted_at is not null
      )
      and not exists (
        select 1 from public.user_blocks b
        where (b.blocker_id = auth.uid() and b.blocked_id = p.author_id)
           or (b.blocker_id = p.author_id and b.blocked_id = auth.uid())
      )
      and (
        p_published_before is null
        or (p.published_at, p.id) < (p_published_before, p_id_before)
      )
  )
  select c.post_id, c.matched_author_ids, c.matched_topic_keys, c.published_at
  from candidate c
  where p_source in ('all', 'authors', 'topics')
    and (
      (p_source in ('all', 'authors') and cardinality(c.matched_author_ids) > 0)
      or
      (p_source in ('all', 'topics') and cardinality(c.matched_topic_keys) > 0)
    )
  order by c.published_at desc, c.post_id desc
  limit least(greatest(p_limit, 1), 30);
$$;

revoke all on function public.get_subscription_feed_candidates(
  text, text, timestamptz, uuid, integer
) from public, anon;
grant execute on function public.get_subscription_feed_candidates(
  text, text, timestamptz, uuid, integer
) to authenticated;
